package AppCafeteria.GUI;

/**
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *   DEVELOPED BY STELLIOX.COM                                     *
 *   ECUADOR - LOJA - 2016                                         *
 *   @author stelliox.com                                          *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 */

public class MainView extends javax.swing.JFrame {
    OrderView orderView = new OrderView();
    InventoryView inventoryView = new InventoryView();
    TableView tableView = new TableView();
    
    public MainView() {        
        initComponents();
        
        opOrderMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        opOrder = new javax.swing.JMenu();
        opInventory = new javax.swing.JMenu();
        opTable = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 650));

        opOrder.setText("Solicitar Pedido");
        opOrder.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        opOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opOrderMouseClicked(evt);
            }
        });
        jMenuBar1.add(opOrder);

        opInventory.setText("Intentario");
        opInventory.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        opInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opInventoryMouseClicked(evt);
            }
        });
        jMenuBar1.add(opInventory);

        opTable.setText("Mesas");
        opTable.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        opTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opTableMouseClicked(evt);
            }
        });
        jMenuBar1.add(opTable);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opInventoryMouseClicked
        this.remove(tableView);
        this.remove(orderView);
        this.remove(inventoryView);
        this.repaint();
        inventoryView = new InventoryView();
        this.getContentPane().add(inventoryView);
        inventoryView.updateUI();
        this.validate();
    }//GEN-LAST:event_opInventoryMouseClicked

    private void opOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opOrderMouseClicked
        this.remove(tableView);
        this.remove(inventoryView);
        this.remove(orderView);
        this.repaint();
        orderView = new OrderView();
        this.getContentPane().add(orderView);
        orderView.updateUI();
        this.validate();
    }//GEN-LAST:event_opOrderMouseClicked

    private void opTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opTableMouseClicked
        this.remove(tableView);
        this.remove(inventoryView);
        this.remove(orderView);
        this.repaint();
        tableView = new TableView();
        this.getContentPane().add(tableView);
        tableView.updateUI();
        this.validate();
    }//GEN-LAST:event_opTableMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu opInventory;
    private javax.swing.JMenu opOrder;
    private javax.swing.JMenu opTable;
    // End of variables declaration//GEN-END:variables
}
